### ISSUE TITLE
Repeating "Codebook 0 of -1 (-0.0%) columns selected" error 

### ISSUE THREAD

**Issue by mhickle** [RhoInc/web-codebook#219] opened 2017-11-14 15:33 UTC
Repeating "Codebook 0 of -1 (-0.0%) columns selected" error appears when filtering down to the "no rows selected" message then clicking on another Codebook.

**Comment by mhickle** [comment] 2017-11-14 15:34
![1075_10781](https://user-images.githubusercontent.com/31038805/32788497-558e097a-c927-11e7-94f6-1a450814ea00.png)
![1116_6761](https://user-images.githubusercontent.com/31038805/32788499-577a6b3e-c927-11e7-8874-aad6c662472b.png)

**Comment by jwildfire** [comment] 2017-11-17 16:54
Pretty sure this is due to the way the loading icon is handled. That process needs a refactor.

**Comment by jwildfire** [comment] 2017-11-21 17:46
This was caused by a combination of #224 and #221. Closing as duplicate.

**Closed by jwildfire** 2017-11-21 17:46 UTC
Labels: duplicate
